--- @class blink.lib.lsp.server.Opts
--- @field name string Name of the server, used as the key for pulling settings
--- @field default_settings? table | blink.lib.Config Default settings
--- @field init? fun(capabilities: lsp.ServerCapabilities, settings: table) Callback invoked after LSP "initialize", where `result` is a table of `capabilities`
--- @field shutdown? fun() Callback invoked on LSP "shutdown", after all requests have been cancelled
--- @field capabilities? lsp.ServerCapabilities | fun(params: lsp.InitializeParams): lsp.ServerCapabilities LSP capabilities to advertise on initialization
--- @field handlers? blink.lib.lsp.server.Handlers
--- @field notifications? blink.lib.lsp.server.Notifications

--- @class blink.lib.lsp.server.Ctx<R>
--- @field id? integer Request ID, nil for notifications
--- @field notify fun(method: string, params: table) Send a notification to the client
--- @field request fun(method: string, params: table, callback: fun(err: lsp.ResponseError?, result: any)): any, lsp.ResponseError? Send a request to the client
--- @field cancel fun(err?: lsp.ResponseError) Cancel the request
--- @field is_cancelled fun(): boolean Returns true if the request has been cancelled
--- @field respond fun(result: R, err?: lsp.ResponseError) Respond asynchronously
--- @field settings? table

--- @class blink.lib.lsp.server.NotificationCtx
--- @field notify fun(method: string, params: table) Send a notification to the client
--- @field request fun(method: string, params: table, callback: fun(err: lsp.ResponseError?, result: any)) Send a request to the client

--- @class blink.lib.lsp.server.Handlers
---
--- Lifecycle
--- @field shutdown? fun(params: nil, ctx: blink.lib.lsp.server.Ctx<nil>): nil, lsp.ResponseError?
---
--- Workspace
--- @field ['workspace/symbol']? fun(params: lsp.WorkspaceSymbolParams, ctx: blink.lib.lsp.server.Ctx<lsp.WorkspaceSymbol[]|lsp.SymbolInformation[]>): (lsp.WorkspaceSymbol[]|lsp.SymbolInformation[])?, lsp.ResponseError?
--- @field ['workspaceSymbol/resolve']? fun(params: lsp.WorkspaceSymbol, ctx: blink.lib.lsp.server.Ctx<lsp.WorkspaceSymbol>): lsp.WorkspaceSymbol?, lsp.ResponseError?
--- @field ['workspace/executeCommand']? fun(params: lsp.ExecuteCommandParams, ctx: blink.lib.lsp.server.Ctx<any>): any?, lsp.ResponseError?
--- @field ['workspace/willCreateFiles']? fun(params: lsp.CreateFilesParams, ctx: blink.lib.lsp.server.Ctx<lsp.WorkspaceEdit>): lsp.WorkspaceEdit?, lsp.ResponseError?
--- @field ['workspace/willRenameFiles']? fun(params: lsp.RenameFilesParams, ctx: blink.lib.lsp.server.Ctx<lsp.WorkspaceEdit>): lsp.WorkspaceEdit?, lsp.ResponseError?
--- @field ['workspace/willDeleteFiles']? fun(params: lsp.DeleteFilesParams, ctx: blink.lib.lsp.server.Ctx<lsp.WorkspaceEdit>): lsp.WorkspaceEdit?, lsp.ResponseError?
--- @field ['workspace/diagnostic']? fun(params: lsp.WorkspaceDiagnosticParams, ctx: blink.lib.lsp.server.Ctx<lsp.WorkspaceDiagnosticReport>): lsp.WorkspaceDiagnosticReport?, lsp.ResponseError?
---
--- Text Document
--- @field ['textDocument/willSaveWaitUntil']? fun(params: lsp.WillSaveTextDocumentParams, ctx: blink.lib.lsp.server.Ctx<lsp.TextEdit[]>): lsp.TextEdit[]?, lsp.ResponseError?
--- @field ['textDocument/completion']? fun(params: lsp.CompletionParams, ctx: blink.lib.lsp.server.Ctx<lsp.CompletionItem[]|lsp.CompletionList>): (lsp.CompletionItem[]|lsp.CompletionList)?, lsp.ResponseError?
--- @field ['completionItem/resolve']? fun(params: lsp.CompletionItem, ctx: blink.lib.lsp.server.Ctx<lsp.CompletionItem>): lsp.CompletionItem?, lsp.ResponseError?
--- @field ['textDocument/hover']? fun(params: lsp.HoverParams, ctx: blink.lib.lsp.server.Ctx<lsp.Hover>): lsp.Hover?, lsp.ResponseError?
--- @field ['textDocument/signatureHelp']? fun(params: lsp.SignatureHelpParams, ctx: blink.lib.lsp.server.Ctx<lsp.SignatureHelp>): lsp.SignatureHelp?, lsp.ResponseError?
--- @field ['textDocument/declaration']? fun(params: lsp.DeclarationParams, ctx: blink.lib.lsp.server.Ctx<lsp.Declaration|lsp.DeclarationLink[]>): (lsp.Declaration|lsp.DeclarationLink[])?, lsp.ResponseError?
--- @field ['textDocument/definition']? fun(params: lsp.DefinitionParams, ctx: blink.lib.lsp.server.Ctx<lsp.Definition|lsp.DefinitionLink[]>): (lsp.Definition|lsp.DefinitionLink[])?, lsp.ResponseError?
--- @field ['textDocument/typeDefinition']? fun(params: lsp.TypeDefinitionParams, ctx: blink.lib.lsp.server.Ctx<lsp.Definition|lsp.DefinitionLink[]>): (lsp.Definition|lsp.DefinitionLink[])?, lsp.ResponseError?
--- @field ['textDocument/implementation']? fun(params: lsp.ImplementationParams, ctx: blink.lib.lsp.server.Ctx<lsp.Definition|lsp.DefinitionLink[]>): (lsp.Definition|lsp.DefinitionLink[])?, lsp.ResponseError?
--- @field ['textDocument/references']? fun(params: lsp.ReferenceParams, ctx: blink.lib.lsp.server.Ctx<lsp.Location[]>): lsp.Location[]?, lsp.ResponseError?
--- @field ['textDocument/documentHighlight']? fun(params: lsp.DocumentHighlightParams, ctx: blink.lib.lsp.server.Ctx<lsp.DocumentHighlight[]>): lsp.DocumentHighlight[]?, lsp.ResponseError?
--- @field ['textDocument/documentSymbol']? fun(params: lsp.DocumentSymbolParams, ctx: blink.lib.lsp.server.Ctx<lsp.SymbolInformation[]|lsp.DocumentSymbol[]>): (lsp.SymbolInformation[]|lsp.DocumentSymbol[])?, lsp.ResponseError?
--- @field ['textDocument/codeAction']? fun(params: lsp.CodeActionParams, ctx: blink.lib.lsp.server.Ctx<(lsp.Command|lsp.CodeAction)[]>): (lsp.Command|lsp.CodeAction)[]?, lsp.ResponseError?
--- @field ['codeAction/resolve']? fun(params: lsp.CodeAction, ctx: blink.lib.lsp.server.Ctx<lsp.CodeAction>): lsp.CodeAction?, lsp.ResponseError?
--- @field ['textDocument/codeLens']? fun(params: lsp.CodeLensParams, ctx: blink.lib.lsp.server.Ctx<lsp.CodeLens[]>): lsp.CodeLens[]?, lsp.ResponseError?
--- @field ['codeLens/resolve']? fun(params: lsp.CodeLens, ctx: blink.lib.lsp.server.Ctx<lsp.CodeLens>): lsp.CodeLens?, lsp.ResponseError?
--- @field ['textDocument/documentLink']? fun(params: lsp.DocumentLinkParams, ctx: blink.lib.lsp.server.Ctx<lsp.DocumentLink[]>): lsp.DocumentLink[]?, lsp.ResponseError?
--- @field ['documentLink/resolve']? fun(params: lsp.DocumentLink, ctx: blink.lib.lsp.server.Ctx<lsp.DocumentLink>): lsp.DocumentLink?, lsp.ResponseError?
--- @field ['textDocument/documentColor']? fun(params: lsp.DocumentColorParams, ctx: blink.lib.lsp.server.Ctx<lsp.ColorInformation[]>): lsp.ColorInformation[]?, lsp.ResponseError?
--- @field ['textDocument/colorPresentation']? fun(params: lsp.ColorPresentationParams, ctx: blink.lib.lsp.server.Ctx<lsp.ColorPresentation[]>): lsp.ColorPresentation[]?, lsp.ResponseError?
--- @field ['textDocument/formatting']? fun(params: lsp.DocumentFormattingParams, ctx: blink.lib.lsp.server.Ctx<lsp.TextEdit[]>): lsp.TextEdit[]?, lsp.ResponseError?
--- @field ['textDocument/rangeFormatting']? fun(params: lsp.DocumentRangeFormattingParams, ctx: blink.lib.lsp.server.Ctx<lsp.TextEdit[]>): lsp.TextEdit[]?, lsp.ResponseError?
--- @field ['textDocument/rangesFormatting']? fun(params: lsp.DocumentRangesFormattingParams, ctx: blink.lib.lsp.server.Ctx<lsp.TextEdit[]>): lsp.TextEdit[]?, lsp.ResponseError?
--- @field ['textDocument/onTypeFormatting']? fun(params: lsp.DocumentOnTypeFormattingParams, ctx: blink.lib.lsp.server.Ctx<lsp.TextEdit[]>): lsp.TextEdit[]?, lsp.ResponseError?
--- @field ['textDocument/rename']? fun(params: lsp.RenameParams, ctx: blink.lib.lsp.server.Ctx<lsp.WorkspaceEdit>): lsp.WorkspaceEdit?, lsp.ResponseError?
--- @field ['textDocument/prepareRename']? fun(params: lsp.PrepareRenameParams, ctx: blink.lib.lsp.server.Ctx<lsp.PrepareRenameResult>): lsp.PrepareRenameResult?, lsp.ResponseError?
--- @field ['textDocument/foldingRange']? fun(params: lsp.FoldingRangeParams, ctx: blink.lib.lsp.server.Ctx<lsp.FoldingRange[]>): lsp.FoldingRange[]?, lsp.ResponseError?
--- @field ['textDocument/selectionRange']? fun(params: lsp.SelectionRangeParams, ctx: blink.lib.lsp.server.Ctx<lsp.SelectionRange[]>): lsp.SelectionRange[]?, lsp.ResponseError?
--- @field ['textDocument/prepareCallHierarchy']? fun(params: lsp.CallHierarchyPrepareParams, ctx: blink.lib.lsp.server.Ctx<lsp.CallHierarchyItem[]>): lsp.CallHierarchyItem[]?, lsp.ResponseError?
--- @field ['callHierarchy/incomingCalls']? fun(params: lsp.CallHierarchyIncomingCallsParams, ctx: blink.lib.lsp.server.Ctx<lsp.CallHierarchyIncomingCall[]>): lsp.CallHierarchyIncomingCall[]?, lsp.ResponseError?
--- @field ['callHierarchy/outgoingCalls']? fun(params: lsp.CallHierarchyOutgoingCallsParams, ctx: blink.lib.lsp.server.Ctx<lsp.CallHierarchyOutgoingCall[]>): lsp.CallHierarchyOutgoingCall[]?, lsp.ResponseError?
--- @field ['textDocument/prepareTypeHierarchy']? fun(params: lsp.TypeHierarchyPrepareParams, ctx: blink.lib.lsp.server.Ctx<lsp.TypeHierarchyItem[]>): lsp.TypeHierarchyItem[]?, lsp.ResponseError?
--- @field ['typeHierarchy/supertypes']? fun(params: lsp.TypeHierarchySupertypesParams, ctx: blink.lib.lsp.server.Ctx<lsp.TypeHierarchyItem[]>): lsp.TypeHierarchyItem[]?, lsp.ResponseError?
--- @field ['typeHierarchy/subtypes']? fun(params: lsp.TypeHierarchySubtypesParams, ctx: blink.lib.lsp.server.Ctx<lsp.TypeHierarchyItem[]>): lsp.TypeHierarchyItem[]?, lsp.ResponseError?
--- @field ['textDocument/semanticTokens/full']? fun(params: lsp.SemanticTokensParams, ctx: blink.lib.lsp.server.Ctx<lsp.SemanticTokens>): lsp.SemanticTokens?, lsp.ResponseError?
--- @field ['textDocument/semanticTokens/full/delta']? fun(params: lsp.SemanticTokensDeltaParams, ctx: blink.lib.lsp.server.Ctx<lsp.SemanticTokens|lsp.SemanticTokensDelta>): (lsp.SemanticTokens|lsp.SemanticTokensDelta)?, lsp.ResponseError?
--- @field ['textDocument/semanticTokens/range']? fun(params: lsp.SemanticTokensRangeParams, ctx: blink.lib.lsp.server.Ctx<lsp.SemanticTokens>): lsp.SemanticTokens?, lsp.ResponseError?
--- @field ['textDocument/linkedEditingRange']? fun(params: lsp.LinkedEditingRangeParams, ctx: blink.lib.lsp.server.Ctx<lsp.LinkedEditingRanges>): lsp.LinkedEditingRanges?, lsp.ResponseError?
--- @field ['textDocument/moniker']? fun(params: lsp.MonikerParams, ctx: blink.lib.lsp.server.Ctx<lsp.Moniker[]>): lsp.Moniker[]?, lsp.ResponseError?
--- @field ['textDocument/inlayHint']? fun(params: lsp.InlayHintParams, ctx: blink.lib.lsp.server.Ctx<lsp.InlayHint[]>): lsp.InlayHint[]?, lsp.ResponseError?
--- @field ['inlayHint/resolve']? fun(params: lsp.InlayHint, ctx: blink.lib.lsp.server.Ctx<lsp.InlayHint>): lsp.InlayHint?, lsp.ResponseError?
--- @field ['textDocument/inlineValue']? fun(params: lsp.InlineValueParams, ctx: blink.lib.lsp.server.Ctx<lsp.InlineValue[]>): lsp.InlineValue[]?, lsp.ResponseError?
--- @field ['textDocument/inlineCompletion']? fun(params: lsp.InlineCompletionParams, ctx: blink.lib.lsp.server.Ctx<lsp.InlineCompletionItem[]|lsp.InlineCompletionList>): (lsp.InlineCompletionItem[]|lsp.InlineCompletionList)?, lsp.ResponseError?
--- @field ['textDocument/diagnostic']? fun(params: lsp.DocumentDiagnosticParams, ctx: blink.lib.lsp.server.Ctx<lsp.DocumentDiagnosticReport>): lsp.DocumentDiagnosticReport?, lsp.ResponseError?

--- @class blink.lib.lsp.server.Notifications
---
--- Lifecycle
--- @field ['$/progress']? fun(params: lsp.ProgressParams, ctx: blink.lib.lsp.server.NotificationCtx)
--- @field ['$/setTrace']? fun(params: lsp.SetTraceParams, ctx: blink.lib.lsp.server.NotificationCtx)
---
--- Workspace
--- @field ['workspace/didChangeConfiguration']? fun(params: lsp.DidChangeConfigurationParams, ctx: blink.lib.lsp.server.NotificationCtx)
--- @field ['workspace/didChangeWatchedFiles']? fun(params: lsp.DidChangeWatchedFilesParams, ctx: blink.lib.lsp.server.NotificationCtx)
--- @field ['workspace/didChangeWorkspaceFolders']? fun(params: lsp.DidChangeWorkspaceFoldersParams, ctx: blink.lib.lsp.server.NotificationCtx)
--- @field ['workspace/didCreateFiles']? fun(params: lsp.CreateFilesParams, ctx: blink.lib.lsp.server.NotificationCtx)
--- @field ['workspace/didRenameFiles']? fun(params: lsp.RenameFilesParams, ctx: blink.lib.lsp.server.NotificationCtx)
--- @field ['workspace/didDeleteFiles']? fun(params: lsp.DeleteFilesParams, ctx: blink.lib.lsp.server.NotificationCtx)
---
--- Text Document
--- @field ['textDocument/didOpen']? fun(params: lsp.DidOpenTextDocumentParams, ctx: blink.lib.lsp.server.NotificationCtx)
--- @field ['textDocument/didChange']? fun(params: lsp.DidChangeTextDocumentParams, ctx: blink.lib.lsp.server.NotificationCtx)
--- @field ['textDocument/didClose']? fun(params: lsp.DidCloseTextDocumentParams, ctx: blink.lib.lsp.server.NotificationCtx)
--- @field ['textDocument/didSave']? fun(params: lsp.DidSaveTextDocumentParams, ctx: blink.lib.lsp.server.NotificationCtx)
--- @field ['textDocument/willSave']? fun(params: lsp.WillSaveTextDocumentParams, ctx: blink.lib.lsp.server.NotificationCtx)
---
--- Notebook Document
--- @field ['notebookDocument/didOpen']? fun(params: lsp.DidOpenNotebookDocumentParams, ctx: blink.lib.lsp.server.NotificationCtx)
--- @field ['notebookDocument/didChange']? fun(params: lsp.DidChangeNotebookDocumentParams, ctx: blink.lib.lsp.server.NotificationCtx)
--- @field ['notebookDocument/didSave']? fun(params: lsp.DidSaveNotebookDocumentParams, ctx: blink.lib.lsp.server.NotificationCtx)
--- @field ['notebookDocument/didClose']? fun(params: lsp.DidCloseNotebookDocumentParams, ctx: blink.lib.lsp.server.NotificationCtx)
